version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_CREATE_TOPICS: "user-app-user-created:1:1"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
  kafka-rest:
    image: confluentinc/cp-kafka-rest:5.1.2
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 8082
    environment:
      KAFKA_REST_HOST_NAME: 'kafka-rest'
      KAFKA_REST_BOOTSTRAP_SERVERS: 'kafka:9092'
      KAFKA_REST_LISTENERS: 'http://0.0.0.0:8082'
  user-app:
    depends_on:
      - kafka
      - kafka-rest
    image: user-app
    ports:
      - 8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 20s
      timeout: 10s
      retries: 6
