version: 2
jobs:
  build:
    working_directory: ~/micro-service-workshop
    docker:
      - image: openjdk:8
    environment:
      - SBT_VERSION: 1.3.3
    steps:
      - setup_remote_docker
      - run:
          name: Prepare build environment
          command: |
            curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
            dpkg -i sbt-$SBT_VERSION.deb
            rm sbt-$SBT_VERSION.deb
            apt-get update
            apt-get install -y sbt git python-pip
            apt-get install -y apt-transport-https ca-certificates gnupg-agent software-properties-common
            curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
            add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
            apt-get update
            apt-get install docker-ce-cli
            apt-get clean && apt-get autoclean
            pip install docker-compose
      - checkout
      - restore_cache:
          key: sbt-cache
      - run:
          name: Build
          command: cat /dev/null | sbt clean test
      - run:
          name: Docker publish
          command: cat /dev/null | sbt docker:publishLocal
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
